<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\User;
use app\models\UserSearch;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends DefaultController
{
    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Updates an existing User model.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/admin/user/update?id='.$model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['/admin/user']);
    }

    /**
     * Updates an existing User model with new password.
     * @param integer $id
     * @return mixed
     */
    public function actionReset($id)
    {
        $model = $this->findModel($id);

        $pswd = $model->generatePassword();
        if ($model->save()) {
            $model->sendEmail(
                '<strong>This e-mail is notification of the following recent change to your '.Yii::$app->name.' account:</strong><br /><br /><br />'.
			    'Your new password is: '.$pswd.'<br /><br /><br /><br /><br />'.
                'If you did not make this change or authorize someone else to make the change, contact '.Yii::$app->name.
                ' immediately<br><br />This email was automatically generated by '.Yii::$app->name.'. Please do not reply to this message.'
            );

            Yii::$app->session->setFlash('success', 'New password was succesfully reseted.');
        } else {
            Yii::$app->session->setFlash('danger', 'Error was occured while password was reseting.');
        }

        return $this->redirect(['/admin/user/update?id='.$model->id]);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}
